name: Rust
on:
  push: { branches: "master" }
  pull_request: { branches: "*" }
jobs:
  check-fmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: cargo fmt -- --check
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - name: Install Rust nightly
      run: rustup install nightly
    - uses: actions/checkout@v1
    - name: Build
      run: cargo +nightly build --verbose
    - name: Run tests
      run: cargo +nightly test --verbose
    - name: Build examples
      run: cd examples && cargo +nightly build --all-targets --verbose
